In [4]:
# Detail Practice of Python Pandas and NumPy

# Variables and Data Types
x = "Asign Variable"
y = 2
z = 5.5
print(x,y,z)
#alternative
# here we are assigning the multiple values at same line
x,y,z = 'Assign Variable', 2, 5.5
print(x,y,z)

Asign Variable 2 5.5
Assign Variable 2 5.5


In [8]:
# Check data Types 
type(x)
type(y)
type(z)
# we can also use casting to convert one data type to another
w = int(z)
w

5

In [24]:
# string is also working like array/list
# we can play with string let suppose
st = 'Muhammad Adil'
print(st)
# we can grab this string character by character
print(st[0:]) # 0 to till end
print(st[9:]) # from 9th to till end
print(st[:9]) # 0 to to just 8th index

st1 = 'Muhammad'
st2 = 'Adil'
final = st1 + st2 # concatenate the string
print(final)

# we can perform some functionality with string to modify
strr = 'I am a good student that learn ASAP'
strr.upper()
strr.lower()
#important
strr.split(' ') # split string into list
a = "Hello"
print(a.replace("H", "J"))

#important
print('{} Muhammad Adil {name}'.format(a, name='Badshah'))

Muhammad Adil
Muhammad Adil
Adil
Muhammad 
MuhammadAdil
Jello
Hello Muhammad Adil Badshah


In [30]:
# if-else condition
#Indendation is important
x, y = 5, 10
if x>5 and y<10:
    print('Between 5 and 10')
elif x == 5 and y == 10:
    print('Equal to 5 and 10')
else:
    print('Not both')


Equal to 5 and 10


In [47]:
# loops in python
for x in range(0,10):
    print(x)
v = 0
while v <5:
    print(v)
    v+=1

0
1
2
3
4
5
6
7
8
9
0
1
2
3
4


In [54]:
# list 
# most important in python in array term
first = [1, 2, 3, 4, 5]
# two way to acess list
for x in range(len(first)):
    print(first[x])
for x in first:
    print(x)
first.insert(3, "Muhammad")
first.append('Adil')
first
first.pop(2)
first
# many more function we can use to play with list

1
2
3
4
5
1
2
3
4
5


[1, 2, 'Muhammad', 4, 5, 'Adil']

In [71]:
name = [[1,2,3, 4], [4,5,6, 5],[7,8,9, 6]]
for x in name:
    print(x)
print(name[1][2:])

[1, 2, 3, 4]
[4, 5, 6, 5]
[7, 8, 9, 6]
[6, 5]


In [94]:
# list comprehensive **** IMPORTANT ******
fruits = ["apple", "banana", "cherry"]
[print(x) for x in fruits]
number = [1,2,3, 4]
x = [x**2 for x in number if x == 2]
print(x)
squared_numbers = [(lambda x: x**2)(x) for x in number if (x ==2) or (x == 4)]

print(squared_numbers)

apple
banana
cherry
[4]
[4, 16]


In [111]:
# maping 
number = [1,2,3, 4]
new = list(map(lambda x: x+x if x%2 == 0 else x, number))
new

[1, 4, 3, 8]

In [123]:
import json

# a Python object (dict):
x = {
  "name": "John",
  "age": 30,
  "city": "New York"
}

# convert into JSON:
yy = json.dumps(x, indent=4)

# the result is a JSON string:
print(yy)

{
    "name": "John",
    "age": 30,
    "city": "New York"
}


In [128]:
num = input("Enter number 1")
try:
    if l == 1: 
        print('A')
    else:
        print('B')
except:
    print('Incorrect entry')

Enter number 11
Incorrect entry


43.0


In [2]:
# NumPy practice
import numpy as np
# convert list into array
arr = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
np.array(arr)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
# in this way we can make array in numpy
arr2 = np.arange(1,50).reshape(7,7)

In [8]:
np.random.randn(5,5) # random generate array

array([[-0.65047324, -1.45147285,  0.65742178,  0.06386474, -0.50059207],
       [-0.6188161 , -1.15114651, -0.82201705,  1.4895267 ,  0.19520441],
       [-0.6855697 , -2.14478204,  1.18195457, -1.14844461, -2.46891218],
       [-0.88409962,  0.83156868, -0.35811174, -0.65302894,  0.17747843],
       [-1.48795701,  1.69771147, -0.75020033, -0.41525822, -0.19915493]])

In [16]:
# some functionality in numpy
np.max(arr)

16

In [17]:
np.min(arr)

1

In [19]:
np.mean(arr)

8.5

In [20]:
np.std(arr)

4.6097722286464435

In [22]:
arr2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr2[2,5]

20

In [24]:
# Slicing in array
arr2[1:4]

array([[ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28]])

In [25]:
arr2[1:4, 3:]

array([[11, 12, 13, 14],
       [18, 19, 20, 21],
       [25, 26, 27, 28]])

In [29]:
arr2[(arr2>20) & (arr2<40)] #conditional selection ffrom the array

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39])

In [33]:
arr3 = np.ones((5,5))

In [41]:
arr4 = arr3*5 + arr3 # arithmetic operation

In [48]:
np.sqrt(arr4[1:3, 2:])

array([[2.44948974, 2.44948974, 2.44948974],
       [2.44948974, 2.44948974, 2.44948974]])

In [60]:
import pandas as pd

data1 = {
  "name": ["Sally", "Mary", "John"],
  "age": [50, 40, 30]
}

data2 = {
  "qualified": [True, False, False]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

newdf = df1.join(df2)

In [61]:
newdf

name  age  qualified
0  Sally   50       True
1   Mary   40      False
2   John   30      False